/**
 * Seed lexicon: ~300 highest-value German lemmas for the beginner→A2
 * zone, ordered by approximate OpenSubtitles-de frequency rank
 * (HermitDave lists; spoken/colloquial register, the register the app
 * teaches — see custom-teaching-methodology.md #12). Rank is an
 * ordinal approximation: inflected forms are folded into their lemma,
 * so lemma ranks sit slightly above raw surface-form ranks.
 *
 * Conventions:
 * - Personal pronoun case forms live under the nominative lexeme
 *   ("mich"/"mir" are forms of "ich:PRON").
 * - der/die/das is one DET lexeme (lemma "der") carrying all forms.
 * - Separable verbs (tag "separable") list the joined subordinate-
 *   clause forms ("aufstehe"), the participle and the zu-infinitive;
 *   split main-clause forms ("stehe … auf") are the syntax layer's
 *   job, not the token matcher's.
 * - Modal particles carry tag "particle"; regional/slangy ones add
 *   "colloquial" (the Erlangen spoken-register thread).
 * - Contractions (hab', gibt's, im, zum …) are expanded by
 *   tokenize.ts, so they are not duplicated here.
 */

import type { Lexeme } from "./types";

export const SEED_LEXICON: Lexeme[] = [
  // ── Core function words and top verbs (ranks ~1–70) ──────────────
  { id: "ich:PRON", lemma: "ich", pos: "PRON", english: "I", rank: 1, cefr: "A1", forms: ["mich", "mir"] },
  { id: "sein:V", lemma: "sein", pos: "V", english: "to be", rank: 2, cefr: "A1", forms: ["bin", "bist", "ist", "sind", "seid", "war", "gewesen"], tags: ["finite-aux"] },
  { id: "du:PRON", lemma: "du", pos: "PRON", english: "you (informal)", rank: 3, cefr: "A1", forms: ["dich", "dir"] },
  { id: "der:DET", lemma: "der", pos: "DET", english: "the", rank: 4, cefr: "A1", forms: ["die", "das", "den", "dem", "des"] },
  { id: "nicht:ADV", lemma: "nicht", pos: "ADV", english: "not", rank: 5, cefr: "A1", forms: [] },
  { id: "es:PRON", lemma: "es", pos: "PRON", english: "it", rank: 6, cefr: "A1", forms: [] },
  { id: "und:CONJ", lemma: "und", pos: "CONJ", english: "and", rank: 7, cefr: "A1", forms: [] },
  { id: "sie:PRON", lemma: "sie", pos: "PRON", english: "she; they", rank: 8, cefr: "A1", forms: ["ihnen"] },
  { id: "wir:PRON", lemma: "wir", pos: "PRON", english: "we", rank: 9, cefr: "A1", forms: ["uns"] },
  { id: "zu:PREP", lemma: "zu", pos: "PREP", english: "to; too (zu viel)", rank: 10, cefr: "A1", forms: [] },
  { id: "ein:DET", lemma: "ein", pos: "DET", english: "a, an; one", rank: 11, cefr: "A1", forms: ["eine", "einen", "einem", "einer", "eines"] },
  { id: "er:PRON", lemma: "er", pos: "PRON", english: "he", rank: 12, cefr: "A1", forms: ["ihn", "ihm"] },
  { id: "in:PREP", lemma: "in", pos: "PREP", english: "in, into", rank: 13, cefr: "A1", forms: [] },
  { id: "haben:V", lemma: "haben", pos: "V", english: "to have", rank: 14, cefr: "A1", forms: ["habe", "hast", "hat", "habt", "hatte", "gehabt"], tags: ["finite-aux"] },
  { id: "ja:INTJ", lemma: "ja", pos: "INTJ", english: "yes; (particle) as we both know", rank: 15, cefr: "A1", forms: [], tags: ["particle"] },
  { id: "was:PRON", lemma: "was", pos: "PRON", english: "what; (spoken) something", rank: 16, cefr: "A1", forms: [] },
  { id: "wie:ADV", lemma: "wie", pos: "ADV", english: "how; like, as", rank: 17, cefr: "A1", forms: [] },
  { id: "mit:PREP", lemma: "mit", pos: "PREP", english: "with", rank: 18, cefr: "A1", forms: [] },
  { id: "auf:PREP", lemma: "auf", pos: "PREP", english: "on, onto", rank: 19, cefr: "A1", forms: [] },
  { id: "so:ADV", lemma: "so", pos: "ADV", english: "so; like this", rank: 20, cefr: "A1", forms: [] },
  { id: "dass:CONJ", lemma: "dass", pos: "CONJ", english: "that", rank: 21, cefr: "A1", forms: [], tags: ["subordinating"] },
  { id: "sehr:ADV", lemma: "sehr", pos: "ADV", english: "very", rank: 22, cefr: "A1", forms: [] },
  { id: "hier:ADV", lemma: "hier", pos: "ADV", english: "here", rank: 23, cefr: "A1", forms: [] },
  { id: "aber:CONJ", lemma: "aber", pos: "CONJ", english: "but", rank: 24, cefr: "A1", forms: [] },
  { id: "wenn:CONJ", lemma: "wenn", pos: "CONJ", english: "if; when(ever)", rank: 25, cefr: "A1", forms: [], tags: ["subordinating"] },
  { id: "für:PREP", lemma: "für", pos: "PREP", english: "for", rank: 26, cefr: "A1", forms: [] },
  { id: "an:PREP", lemma: "an", pos: "PREP", english: "at, on (vertical)", rank: 27, cefr: "A1", forms: [] },
  { id: "von:PREP", lemma: "von", pos: "PREP", english: "from, of", rank: 28, cefr: "A1", forms: [] },
  { id: "nein:INTJ", lemma: "nein", pos: "INTJ", english: "no", rank: 29, cefr: "A1", forms: ["nee", "nö"] },
  { id: "noch:ADV", lemma: "noch", pos: "ADV", english: "still; yet; another", rank: 30, cefr: "A1", forms: [] },
  { id: "mal:PART", lemma: "mal", pos: "PART", english: "(particle) just, briefly (guck mal); times", rank: 31, cefr: "A1", forms: [], tags: ["particle"] },
  { id: "gut:ADJ", lemma: "gut", pos: "ADJ", english: "good; well", rank: 32, cefr: "A1", forms: ["gute", "guten", "guter", "gutes", "besser", "besten"] },
  { id: "man:PRON", lemma: "man", pos: "PRON", english: "one, you (impersonal)", rank: 33, cefr: "A1", forms: [] },
  { id: "aus:PREP", lemma: "aus", pos: "PREP", english: "out of, from", rank: 34, cefr: "A1", forms: [] },
  { id: "wissen:V", lemma: "wissen", pos: "V", english: "to know (facts)", rank: 35, cefr: "A1", forms: ["weiß", "weißt", "wisst", "wusste", "gewusst"] },
  { id: "können:V", lemma: "können", pos: "V", english: "can, to be able to", rank: 36, cefr: "A1", forms: ["kann", "kannst", "könnt", "konnte", "könnte"], tags: ["modal"] },
  { id: "oder:CONJ", lemma: "oder", pos: "CONJ", english: "or; …, right? (tag)", rank: 37, cefr: "A1", forms: [] },
  { id: "jetzt:ADV", lemma: "jetzt", pos: "ADV", english: "now", rank: 38, cefr: "A1", forms: [] },
  { id: "nach:PREP", lemma: "nach", pos: "PREP", english: "after; to (places)", rank: 39, cefr: "A1", forms: [] },
  { id: "dann:ADV", lemma: "dann", pos: "ADV", english: "then", rank: 40, cefr: "A1", forms: [] },
  { id: "doch:PART", lemma: "doch", pos: "PART", english: "yes it is! (contradicting); (particle) emphasis", rank: 41, cefr: "A1", forms: [], tags: ["particle"] },
  { id: "auch:ADV", lemma: "auch", pos: "ADV", english: "also, too", rank: 42, cefr: "A1", forms: [] },
  { id: "nur:ADV", lemma: "nur", pos: "ADV", english: "only", rank: 43, cefr: "A1", forms: [] },
  { id: "wollen:V", lemma: "wollen", pos: "V", english: "to want", rank: 44, cefr: "A1", forms: ["will", "willst", "wollt", "wollte"], tags: ["modal"] },
  { id: "da:ADV", lemma: "da", pos: "ADV", english: "there; (spoken) then/since", rank: 45, cefr: "A1", forms: [] },
  { id: "bei:PREP", lemma: "bei", pos: "PREP", english: "at, near, with (at sb's place)", rank: 46, cefr: "A1", forms: [] },
  { id: "um:PREP", lemma: "um", pos: "PREP", english: "at (time); around", rank: 47, cefr: "A1", forms: [] },
  { id: "schon:ADV", lemma: "schon", pos: "ADV", english: "already; (particle) it'll be fine (wird schon)", rank: 48, cefr: "A1", forms: [], tags: ["particle"] },
  { id: "alles:PRON", lemma: "alles", pos: "PRON", english: "everything", rank: 49, cefr: "A1", forms: [] },
  { id: "mein:DET", lemma: "mein", pos: "DET", english: "my", rank: 50, cefr: "A1", forms: ["meine", "meinen", "meinem", "meiner", "meins"] },
  { id: "kein:DET", lemma: "kein", pos: "DET", english: "no, not a", rank: 51, cefr: "A1", forms: ["keine", "keinen", "keinem", "keiner", "keins"] },
  { id: "werden:V", lemma: "werden", pos: "V", english: "to become; will (future)", rank: 52, cefr: "A1", forms: ["werde", "wirst", "wird", "wurde", "geworden"], tags: ["finite-aux"] },
  { id: "etwas:PRON", lemma: "etwas", pos: "PRON", english: "something; a bit", rank: 53, cefr: "A1", forms: [] },
  { id: "nichts:PRON", lemma: "nichts", pos: "PRON", english: "nothing", rank: 54, cefr: "A1", forms: ["nix"] },
  { id: "müssen:V", lemma: "müssen", pos: "V", english: "must, to have to", rank: 55, cefr: "A1", forms: ["muss", "musst", "müsst", "musste"], tags: ["modal"] },
  { id: "wer:PRON", lemma: "wer", pos: "PRON", english: "who", rank: 56, cefr: "A1", forms: ["wen", "wem"] },
  { id: "immer:ADV", lemma: "immer", pos: "ADV", english: "always", rank: 57, cefr: "A1", forms: [] },
  { id: "gehen:V", lemma: "gehen", pos: "V", english: "to go, to walk", rank: 58, cefr: "A1", forms: ["gehe", "gehst", "geht", "ging", "gegangen"] },
  { id: "machen:V", lemma: "machen", pos: "V", english: "to make, to do", rank: 59, cefr: "A1", forms: ["mache", "machst", "macht", "gemacht"] },
  { id: "Sie:PRON", lemma: "Sie", pos: "PRON", english: "you (formal)", rank: 60, cefr: "A1", forms: ["ihnen"] },
  { id: "ihr:PRON", lemma: "ihr", pos: "PRON", english: "you (plural, informal)", rank: 61, cefr: "A1", forms: ["euch"] },
  { id: "kommen:V", lemma: "kommen", pos: "V", english: "to come", rank: 62, cefr: "A1", forms: ["komme", "kommst", "kommt", "kam", "gekommen"] },
  { id: "wo:ADV", lemma: "wo", pos: "ADV", english: "where", rank: 63, cefr: "A1", forms: [] },
  { id: "sehen:V", lemma: "sehen", pos: "V", english: "to see", rank: 64, cefr: "A1", forms: ["sehe", "siehst", "sieht", "sah", "gesehen"] },
  { id: "lassen:V", lemma: "lassen", pos: "V", english: "to let, to leave (sth somewhere)", rank: 65, cefr: "A1", forms: ["lasse", "lässt", "lasst", "ließ", "gelassen"] },
  { id: "tun:V", lemma: "tun", pos: "V", english: "to do", rank: 66, cefr: "A1", forms: ["tue", "tust", "tut", "getan"] },
  { id: "sagen:V", lemma: "sagen", pos: "V", english: "to say", rank: 67, cefr: "A1", forms: ["sage", "sagst", "sagt", "gesagt"] },
  { id: "dein:DET", lemma: "dein", pos: "DET", english: "your (informal)", rank: 68, cefr: "A1", forms: ["deine", "deinen", "deinem", "deiner", "deins"] },
  { id: "sich:PRON", lemma: "sich", pos: "PRON", english: "oneself (reflexive)", rank: 69, cefr: "A1", forms: [] },
  { id: "mehr:ADV", lemma: "mehr", pos: "ADV", english: "more", rank: 70, cefr: "A1", forms: [] },

  // ── Remaining function words, particles, question words (~71–130) ─
  { id: "wieder:ADV", lemma: "wieder", pos: "ADV", english: "again", rank: 71, cefr: "A1", forms: [] },
  { id: "vielleicht:ADV", lemma: "vielleicht", pos: "ADV", english: "maybe, perhaps", rank: 72, cefr: "A1", forms: [] },
  { id: "danke:INTJ", lemma: "danke", pos: "INTJ", english: "thanks", rank: 73, cefr: "A1", forms: [] },
  { id: "bitte:INTJ", lemma: "bitte", pos: "INTJ", english: "please; you're welcome; pardon?", rank: 74, cefr: "A1", forms: [] },
  { id: "denken:V", lemma: "denken", pos: "V", english: "to think", rank: 75, cefr: "A1", forms: ["denke", "denkst", "denkt", "dachte", "gedacht"] },
  { id: "dieser:DET", lemma: "dieser", pos: "DET", english: "this, these", rank: 76, cefr: "A1", forms: ["diese", "diesen", "diesem", "dieses", "dies"] },
  { id: "geben:V", lemma: "geben", pos: "V", english: "to give; es gibt = there is", rank: 77, cefr: "A1", forms: ["gebe", "gibst", "gibt", "gab", "gegeben"] },
  { id: "warum:ADV", lemma: "warum", pos: "ADV", english: "why", rank: 78, cefr: "A1", forms: ["wieso"] },
  { id: "verstehen:V", lemma: "verstehen", pos: "V", english: "to understand", rank: 79, cefr: "A1", forms: ["verstehe", "verstehst", "versteht", "verstanden"] },
  { id: "sprechen:V", lemma: "sprechen", pos: "V", english: "to speak", rank: 80, cefr: "A1", forms: ["spreche", "sprichst", "spricht", "sprach", "gesprochen"] },
  { id: "brauchen:V", lemma: "brauchen", pos: "V", english: "to need", rank: 81, cefr: "A1", forms: ["brauche", "brauchst", "braucht", "gebraucht"] },
  { id: "sollen:V", lemma: "sollen", pos: "V", english: "should, to be supposed to", rank: 82, cefr: "A1", forms: ["soll", "sollst", "sollt", "sollte"], tags: ["modal"] },
  { id: "über:PREP", lemma: "über", pos: "PREP", english: "over, above; about", rank: 83, cefr: "A1", forms: [] },
  { id: "vor:PREP", lemma: "vor", pos: "PREP", english: "in front of; before; ago", rank: 84, cefr: "A1", forms: [] },
  { id: "wann:ADV", lemma: "wann", pos: "ADV", english: "when (question)", rank: 85, cefr: "A1", forms: [] },
  { id: "sein:DET", lemma: "sein", pos: "DET", english: "his; its", rank: 86, cefr: "A1", forms: ["seine", "seinen", "seinem", "seiner", "seins"] },
  { id: "ihr:DET", lemma: "ihr", pos: "DET", english: "her; their; your (formal: Ihr)", rank: 87, cefr: "A1", forms: ["ihre", "ihren", "ihrem", "ihrer"] },
  { id: "glauben:V", lemma: "glauben", pos: "V", english: "to believe, to think", rank: 88, cefr: "A1", forms: ["glaube", "glaubst", "glaubt", "geglaubt"] },
  { id: "stehen:V", lemma: "stehen", pos: "V", english: "to stand", rank: 89, cefr: "A1", forms: ["stehe", "stehst", "steht", "stand", "gestanden"] },
  { id: "heißen:V", lemma: "heißen", pos: "V", english: "to be called", rank: 90, cefr: "A1", forms: ["heiße", "heißt", "hieß"] },
  { id: "dürfen:V", lemma: "dürfen", pos: "V", english: "may, to be allowed to", rank: 91, cefr: "A1", forms: ["darf", "darfst", "dürft", "durfte"], tags: ["modal"] },
  { id: "mögen:V", lemma: "mögen", pos: "V", english: "to like; möchte = would like", rank: 92, cefr: "A1", forms: ["mag", "magst", "möchte", "möchtest", "möchten", "mochte"], tags: ["modal"] },
  { id: "unter:PREP", lemma: "unter", pos: "PREP", english: "under; among", rank: 93, cefr: "A1", forms: [] },
  { id: "ohne:PREP", lemma: "ohne", pos: "PREP", english: "without", rank: 94, cefr: "A1", forms: [] },
  { id: "gegen:PREP", lemma: "gegen", pos: "PREP", english: "against; around (time)", rank: 95, cefr: "A1", forms: [] },
  { id: "hallo:INTJ", lemma: "hallo", pos: "INTJ", english: "hello", rank: 96, cefr: "A1", forms: ["hi", "moin"] },
  { id: "nehmen:V", lemma: "nehmen", pos: "V", english: "to take", rank: 97, cefr: "A1", forms: ["nehme", "nimmst", "nimmt", "nahm", "genommen"] },
  { id: "finden:V", lemma: "finden", pos: "V", english: "to find; to think (opinion)", rank: 98, cefr: "A1", forms: ["finde", "findest", "findet", "fand", "gefunden"] },
  { id: "halt:PART", lemma: "halt", pos: "PART", english: "(particle) just, simply — that's how it is", rank: 99, cefr: "A2", forms: [], tags: ["particle", "colloquial"] },
  { id: "eben:PART", lemma: "eben", pos: "PART", english: "(particle) exactly, that's the point; just now", rank: 100, cefr: "A2", forms: [], tags: ["particle"] },
  { id: "na:PART", lemma: "na", pos: "PART", english: "well… (na ja, na klar, na und?)", rank: 101, cefr: "A2", forms: ["naja"], tags: ["particle", "colloquial"] },
  { id: "denn:CONJ", lemma: "denn", pos: "CONJ", english: "for, because (coordinating)", rank: 102, cefr: "A1", forms: [] },
  { id: "denn:PART", lemma: "denn", pos: "PART", english: "(particle) softens questions (was ist denn los?)", rank: 103, cefr: "A1", forms: [], tags: ["particle"] },
  { id: "weil:CONJ", lemma: "weil", pos: "CONJ", english: "because", rank: 104, cefr: "A1", forms: [], tags: ["subordinating"] },
  { id: "ob:CONJ", lemma: "ob", pos: "CONJ", english: "whether, if", rank: 105, cefr: "A1", forms: [], tags: ["subordinating"] },
  { id: "als:CONJ", lemma: "als", pos: "CONJ", english: "when (single past event); than; as", rank: 106, cefr: "A2", forms: [], tags: ["subordinating"] },
  { id: "obwohl:CONJ", lemma: "obwohl", pos: "CONJ", english: "although", rank: 107, cefr: "A2", forms: [], tags: ["subordinating"] },
  { id: "seit:PREP", lemma: "seit", pos: "PREP", english: "since, for (time)", rank: 108, cefr: "A1", forms: [] },
  { id: "zwischen:PREP", lemma: "zwischen", pos: "PREP", english: "between", rank: 109, cefr: "A1", forms: [] },
  { id: "hinter:PREP", lemma: "hinter", pos: "PREP", english: "behind", rank: 110, cefr: "A1", forms: [] },
  { id: "neben:PREP", lemma: "neben", pos: "PREP", english: "next to", rank: 111, cefr: "A1", forms: [] },
  { id: "durch:PREP", lemma: "durch", pos: "PREP", english: "through", rank: 112, cefr: "A1", forms: [] },
  { id: "jeder:DET", lemma: "jeder", pos: "DET", english: "every, each", rank: 113, cefr: "A1", forms: ["jede", "jeden", "jedem", "jedes"] },
  { id: "alle:PRON", lemma: "alle", pos: "PRON", english: "all, everyone", rank: 114, cefr: "A1", forms: ["allen", "aller"] },
  { id: "jemand:PRON", lemma: "jemand", pos: "PRON", english: "someone", rank: 115, cefr: "A1", forms: ["jemanden", "jemandem"] },
  { id: "niemand:PRON", lemma: "niemand", pos: "PRON", english: "no one", rank: 116, cefr: "A1", forms: ["niemanden", "niemandem"] },
  { id: "welcher:DET", lemma: "welcher", pos: "DET", english: "which", rank: 117, cefr: "A1", forms: ["welche", "welchen", "welchem", "welches"] },
  { id: "unser:DET", lemma: "unser", pos: "DET", english: "our", rank: 118, cefr: "A1", forms: ["unsere", "unseren", "unserem", "unserer"] },
  { id: "euer:DET", lemma: "euer", pos: "DET", english: "your (plural)", rank: 119, cefr: "A1", forms: ["eure", "euren", "eurem", "eurer"] },
  { id: "woher:ADV", lemma: "woher", pos: "ADV", english: "where from", rank: 120, cefr: "A1", forms: [] },
  { id: "wohin:ADV", lemma: "wohin", pos: "ADV", english: "where to", rank: 121, cefr: "A1", forms: [] },
  { id: "wie viel:ADV", lemma: "wie viel", pos: "ADV", english: "how much / how many", rank: 122, cefr: "A1", forms: ["wieviel", "wieviele"] },
  { id: "eh:PART", lemma: "eh", pos: "PART", english: "(particle) anyway (ist eh egal)", rank: 123, cefr: "A2", forms: [], tags: ["particle", "colloquial"] },
  { id: "gell:PART", lemma: "gell", pos: "PART", english: "right?, isn't it? (southern tag)", rank: 124, cefr: "A2", forms: ["gelle", "gel"], tags: ["particle", "colloquial"] },
  { id: "okay:INTJ", lemma: "okay", pos: "INTJ", english: "okay", rank: 125, cefr: "A1", forms: ["ok"], tags: ["colloquial"] },
  { id: "genau:ADV", lemma: "genau", pos: "ADV", english: "exactly (also as answer)", rank: 126, cefr: "A1", forms: [] },
  { id: "natürlich:ADV", lemma: "natürlich", pos: "ADV", english: "of course; natural(ly)", rank: 127, cefr: "A1", forms: [] },
  { id: "leider:ADV", lemma: "leider", pos: "ADV", english: "unfortunately", rank: 128, cefr: "A1", forms: [] },
  { id: "essen:V", lemma: "essen", pos: "V", english: "to eat", rank: 129, cefr: "A1", forms: ["esse", "isst", "esst", "gegessen"] },
  { id: "trinken:V", lemma: "trinken", pos: "V", english: "to drink", rank: 130, cefr: "A1", forms: ["trinke", "trinkst", "trinkt", "getrunken"] },

  // ── Everyday verbs, adverbs, adjectives (~131–204) ────────────────
  { id: "heute:ADV", lemma: "heute", pos: "ADV", english: "today", rank: 131, cefr: "A1", forms: [] },
  { id: "morgen:ADV", lemma: "morgen", pos: "ADV", english: "tomorrow", rank: 132, cefr: "A1", forms: [] },
  { id: "gestern:ADV", lemma: "gestern", pos: "ADV", english: "yesterday", rank: 133, cefr: "A1", forms: [] },
  { id: "helfen:V", lemma: "helfen", pos: "V", english: "to help", rank: 134, cefr: "A1", forms: ["helfe", "hilfst", "hilft", "geholfen"] },
  { id: "fragen:V", lemma: "fragen", pos: "V", english: "to ask", rank: 135, cefr: "A1", forms: ["frage", "fragst", "fragt", "gefragt"] },
  { id: "hören:V", lemma: "hören", pos: "V", english: "to hear, to listen", rank: 136, cefr: "A1", forms: ["höre", "hörst", "hört", "gehört"] },
  { id: "spielen:V", lemma: "spielen", pos: "V", english: "to play", rank: 137, cefr: "A1", forms: ["spiele", "spielst", "spielt", "gespielt"] },
  { id: "lernen:V", lemma: "lernen", pos: "V", english: "to learn", rank: 138, cefr: "A1", forms: ["lerne", "lernst", "lernt", "gelernt"] },
  { id: "wohnen:V", lemma: "wohnen", pos: "V", english: "to live (reside)", rank: 139, cefr: "A1", forms: ["wohne", "wohnst", "wohnt", "gewohnt"] },
  { id: "arbeiten:V", lemma: "arbeiten", pos: "V", english: "to work", rank: 140, cefr: "A1", forms: ["arbeite", "arbeitest", "arbeitet", "gearbeitet"] },
  { id: "kaufen:V", lemma: "kaufen", pos: "V", english: "to buy", rank: 141, cefr: "A1", forms: ["kaufe", "kaufst", "kauft", "gekauft"] },
  { id: "fahren:V", lemma: "fahren", pos: "V", english: "to drive, to ride, to go (vehicle)", rank: 142, cefr: "A1", forms: ["fahre", "fährst", "fährt", "gefahren"] },
  { id: "laufen:V", lemma: "laufen", pos: "V", english: "to run; to walk", rank: 143, cefr: "A1", forms: ["laufe", "läufst", "läuft", "gelaufen"] },
  { id: "schlafen:V", lemma: "schlafen", pos: "V", english: "to sleep", rank: 144, cefr: "A1", forms: ["schlafe", "schläfst", "schläft", "geschlafen"] },
  { id: "lesen:V", lemma: "lesen", pos: "V", english: "to read", rank: 145, cefr: "A1", forms: ["lese", "liest", "gelesen"] },
  { id: "schreiben:V", lemma: "schreiben", pos: "V", english: "to write", rank: 146, cefr: "A1", forms: ["schreibe", "schreibst", "schreibt", "geschrieben"] },
  { id: "warten:V", lemma: "warten", pos: "V", english: "to wait", rank: 147, cefr: "A1", forms: ["warte", "wartest", "wartet", "gewartet"] },
  { id: "suchen:V", lemma: "suchen", pos: "V", english: "to look for", rank: 148, cefr: "A1", forms: ["suche", "suchst", "sucht", "gesucht"] },
  { id: "zeigen:V", lemma: "zeigen", pos: "V", english: "to show", rank: 149, cefr: "A1", forms: ["zeige", "zeigst", "zeigt", "gezeigt"] },
  { id: "bleiben:V", lemma: "bleiben", pos: "V", english: "to stay", rank: 150, cefr: "A1", forms: ["bleibe", "bleibst", "bleibt", "geblieben"] },
  { id: "liegen:V", lemma: "liegen", pos: "V", english: "to lie, to be located", rank: 151, cefr: "A1", forms: ["liege", "liegst", "liegt", "gelegen"] },
  { id: "bringen:V", lemma: "bringen", pos: "V", english: "to bring", rank: 152, cefr: "A1", forms: ["bringe", "bringst", "bringt", "gebracht"] },
  { id: "treffen:V", lemma: "treffen", pos: "V", english: "to meet", rank: 153, cefr: "A1", forms: ["treffe", "triffst", "trifft", "getroffen"] },
  { id: "bekommen:V", lemma: "bekommen", pos: "V", english: "to get, to receive", rank: 154, cefr: "A1", forms: ["bekomme", "bekommst", "bekommt", "bekam"] },
  { id: "versuchen:V", lemma: "versuchen", pos: "V", english: "to try", rank: 155, cefr: "A2", forms: ["versuche", "versuchst", "versucht"] },
  { id: "passieren:V", lemma: "passieren", pos: "V", english: "to happen", rank: 156, cefr: "A2", forms: ["passiert", "passierte"] },
  { id: "gefallen:V", lemma: "gefallen", pos: "V", english: "to please (das gefällt mir = I like it)", rank: 157, cefr: "A1", forms: ["gefällt", "gefiel"] },
  { id: "erklären:V", lemma: "erklären", pos: "V", english: "to explain", rank: 158, cefr: "A2", forms: ["erkläre", "erklärst", "erklärt"] },
  { id: "freuen:V", lemma: "freuen", pos: "V", english: "sich freuen = to be glad, to look forward", rank: 159, cefr: "A1", forms: ["freue", "freust", "freut", "gefreut"] },
  { id: "leben:V", lemma: "leben", pos: "V", english: "to live", rank: 160, cefr: "A1", forms: ["lebe", "lebst", "lebt", "gelebt"] },
  { id: "kochen:V", lemma: "kochen", pos: "V", english: "to cook", rank: 161, cefr: "A1", forms: ["koche", "kochst", "kocht", "gekocht"] },
  { id: "kosten:V", lemma: "kosten", pos: "V", english: "to cost", rank: 162, cefr: "A1", forms: ["kostet", "gekostet"] },
  { id: "schmecken:V", lemma: "schmecken", pos: "V", english: "to taste (good)", rank: 163, cefr: "A1", forms: ["schmeckt", "geschmeckt"] },
  { id: "gucken:V", lemma: "gucken", pos: "V", english: "to look (colloquial)", rank: 164, cefr: "A2", forms: ["gucke", "guckst", "guckt", "geguckt", "guck"], tags: ["colloquial"] },
  { id: "kriegen:V", lemma: "kriegen", pos: "V", english: "to get (colloquial)", rank: 165, cefr: "A2", forms: ["kriege", "kriegst", "kriegt", "gekriegt"], tags: ["colloquial"] },
  { id: "aufstehen:V", lemma: "aufstehen", pos: "V", english: "to get up", rank: 166, cefr: "A1", forms: ["aufgestanden", "aufzustehen", "aufstehe", "aufstehst", "aufsteht"], tags: ["separable"] },
  { id: "anfangen:V", lemma: "anfangen", pos: "V", english: "to begin", rank: 167, cefr: "A1", forms: ["angefangen", "anzufangen", "anfange", "anfängst", "anfängt"], tags: ["separable"] },
  { id: "aufhören:V", lemma: "aufhören", pos: "V", english: "to stop", rank: 168, cefr: "A2", forms: ["aufgehört", "aufzuhören", "aufhöre", "aufhörst", "aufhört"], tags: ["separable"] },
  { id: "anrufen:V", lemma: "anrufen", pos: "V", english: "to call (phone)", rank: 169, cefr: "A1", forms: ["angerufen", "anzurufen", "anrufe", "anrufst", "anruft"], tags: ["separable"] },
  { id: "aussehen:V", lemma: "aussehen", pos: "V", english: "to look (appearance)", rank: 170, cefr: "A1", forms: ["ausgesehen", "aussehe", "aussiehst", "aussieht"], tags: ["separable"] },
  { id: "ankommen:V", lemma: "ankommen", pos: "V", english: "to arrive", rank: 171, cefr: "A1", forms: ["angekommen", "ankomme", "ankommst", "ankommt"], tags: ["separable"] },
  { id: "mitkommen:V", lemma: "mitkommen", pos: "V", english: "to come along", rank: 172, cefr: "A1", forms: ["mitgekommen", "mitkomme", "mitkommst", "mitkommt"], tags: ["separable"] },
  { id: "einkaufen:V", lemma: "einkaufen", pos: "V", english: "to go shopping", rank: 173, cefr: "A1", forms: ["eingekauft", "einzukaufen", "einkaufe", "einkaufst", "einkauft"], tags: ["separable"] },
  { id: "viel:ADV", lemma: "viel", pos: "ADV", english: "much, a lot; many (viele)", rank: 174, cefr: "A1", forms: ["viele", "vielen", "vieles"] },
  { id: "wenig:ADV", lemma: "wenig", pos: "ADV", english: "little, few", rank: 175, cefr: "A1", forms: ["wenige", "weniger"] },
  { id: "gern:ADV", lemma: "gern", pos: "ADV", english: "gladly (ich trinke gern… = I like drinking…)", rank: 176, cefr: "A1", forms: ["gerne", "lieber"] },
  { id: "gerade:ADV", lemma: "gerade", pos: "ADV", english: "right now, just; straight", rank: 177, cefr: "A1", forms: ["grad", "grade"] },
  { id: "zusammen:ADV", lemma: "zusammen", pos: "ADV", english: "together", rank: 178, cefr: "A1", forms: [] },
  { id: "oft:ADV", lemma: "oft", pos: "ADV", english: "often", rank: 179, cefr: "A1", forms: [] },
  { id: "manchmal:ADV", lemma: "manchmal", pos: "ADV", english: "sometimes", rank: 180, cefr: "A1", forms: [] },
  { id: "nie:ADV", lemma: "nie", pos: "ADV", english: "never", rank: 181, cefr: "A1", forms: ["niemals"] },
  { id: "früh:ADV", lemma: "früh", pos: "ADV", english: "early", rank: 182, cefr: "A1", forms: ["früher"] },
  { id: "spät:ADV", lemma: "spät", pos: "ADV", english: "late", rank: 183, cefr: "A1", forms: ["später"] },
  { id: "groß:ADJ", lemma: "groß", pos: "ADJ", english: "big, tall", rank: 184, cefr: "A1", forms: ["große", "großen", "größer", "größte"] },
  { id: "klein:ADJ", lemma: "klein", pos: "ADJ", english: "small", rank: 185, cefr: "A1", forms: ["kleine", "kleinen", "kleiner", "kleines"] },
  { id: "neu:ADJ", lemma: "neu", pos: "ADJ", english: "new", rank: 186, cefr: "A1", forms: ["neue", "neuen", "neues"] },
  { id: "alt:ADJ", lemma: "alt", pos: "ADJ", english: "old", rank: 187, cefr: "A1", forms: ["alte", "alten", "älter"] },
  { id: "schön:ADJ", lemma: "schön", pos: "ADJ", english: "beautiful, nice", rank: 188, cefr: "A1", forms: ["schöne", "schönen", "schöner"] },
  { id: "schlecht:ADJ", lemma: "schlecht", pos: "ADJ", english: "bad", rank: 189, cefr: "A1", forms: ["schlechte", "schlechten"] },
  { id: "richtig:ADJ", lemma: "richtig", pos: "ADJ", english: "right, correct; (spoken) really", rank: 190, cefr: "A1", forms: ["richtige", "richtigen"] },
  { id: "falsch:ADJ", lemma: "falsch", pos: "ADJ", english: "wrong", rank: 191, cefr: "A1", forms: ["falsche", "falschen"] },
  { id: "schnell:ADJ", lemma: "schnell", pos: "ADJ", english: "fast", rank: 192, cefr: "A1", forms: ["schnelle", "schneller"] },
  { id: "langsam:ADJ", lemma: "langsam", pos: "ADJ", english: "slow", rank: 193, cefr: "A1", forms: ["langsame", "langsamer"] },
  { id: "müde:ADJ", lemma: "müde", pos: "ADJ", english: "tired", rank: 194, cefr: "A1", forms: ["müden"] },
  { id: "teuer:ADJ", lemma: "teuer", pos: "ADJ", english: "expensive", rank: 195, cefr: "A1", forms: ["teure", "teuren", "teurer"] },
  { id: "billig:ADJ", lemma: "billig", pos: "ADJ", english: "cheap", rank: 196, cefr: "A1", forms: ["billige", "billiger"] },
  { id: "wichtig:ADJ", lemma: "wichtig", pos: "ADJ", english: "important", rank: 197, cefr: "A1", forms: ["wichtige", "wichtigen"] },
  { id: "einfach:ADJ", lemma: "einfach", pos: "ADJ", english: "easy, simple; (spoken) just", rank: 198, cefr: "A1", forms: ["einfache", "einfacher"] },
  { id: "schwer:ADJ", lemma: "schwer", pos: "ADJ", english: "hard, difficult; heavy", rank: 199, cefr: "A1", forms: ["schwere", "schwerer"] },
  { id: "leicht:ADJ", lemma: "leicht", pos: "ADJ", english: "easy; light", rank: 200, cefr: "A1", forms: ["leichte", "leichter"] },
  { id: "toll:ADJ", lemma: "toll", pos: "ADJ", english: "great", rank: 201, cefr: "A1", forms: ["tolle", "tollen"] },
  { id: "super:ADJ", lemma: "super", pos: "ADJ", english: "super, great", rank: 202, cefr: "A1", forms: [] },
  { id: "echt:ADJ", lemma: "echt", pos: "ADJ", english: "real; (colloquial) really (echt jetzt?)", rank: 203, cefr: "A2", forms: ["echte", "echten"], tags: ["colloquial"] },
  { id: "krass:ADJ", lemma: "krass", pos: "ADJ", english: "wild, intense (slang)", rank: 204, cefr: "A2", forms: ["krasse", "krasser"], tags: ["colloquial"] },

  // ── Nouns: everyday life domains (~205–283) ──────────────────────
  { id: "Zeit:N", lemma: "Zeit", pos: "N", gender: "die", plural: "Zeiten", english: "time", rank: 205, cefr: "A1", forms: ["zeiten"] },
  { id: "Tag:N", lemma: "Tag", pos: "N", gender: "der", plural: "Tage", english: "day", rank: 206, cefr: "A1", forms: ["tage", "tagen", "tags"] },
  { id: "Mann:N", lemma: "Mann", pos: "N", gender: "der", plural: "Männer", english: "man; husband", rank: 207, cefr: "A1", forms: ["männer"] },
  { id: "Frau:N", lemma: "Frau", pos: "N", gender: "die", plural: "Frauen", english: "woman; wife; Mrs", rank: 208, cefr: "A1", forms: ["frauen"] },
  { id: "Kind:N", lemma: "Kind", pos: "N", gender: "das", plural: "Kinder", english: "child", rank: 209, cefr: "A1", forms: ["kinder", "kindern"] },
  { id: "Jahr:N", lemma: "Jahr", pos: "N", gender: "das", plural: "Jahre", english: "year", rank: 210, cefr: "A1", forms: ["jahre", "jahren"] },
  { id: "Mensch:N", lemma: "Mensch", pos: "N", gender: "der", plural: "Menschen", english: "human, person", rank: 211, cefr: "A1", forms: ["menschen"] },
  { id: "Leute:N", lemma: "Leute", pos: "N", gender: "die", english: "people (plural only)", rank: 212, cefr: "A1", forms: ["leuten"] },
  { id: "Ding:N", lemma: "Ding", pos: "N", gender: "das", plural: "Dinge", english: "thing", rank: 213, cefr: "A1", forms: ["dinge", "dinger"] },
  { id: "Sache:N", lemma: "Sache", pos: "N", gender: "die", plural: "Sachen", english: "thing, matter; (pl.) stuff", rank: 214, cefr: "A1", forms: ["sachen"] },
  { id: "Haus:N", lemma: "Haus", pos: "N", gender: "das", plural: "Häuser", english: "house", rank: 215, cefr: "A1", forms: ["häuser", "hause"] },
  { id: "Frage:N", lemma: "Frage", pos: "N", gender: "die", plural: "Fragen", english: "question", rank: 216, cefr: "A1", forms: ["fragen"] },
  { id: "Antwort:N", lemma: "Antwort", pos: "N", gender: "die", plural: "Antworten", english: "answer", rank: 217, cefr: "A1", forms: ["antworten"] },
  { id: "Problem:N", lemma: "Problem", pos: "N", gender: "das", plural: "Probleme", english: "problem", rank: 218, cefr: "A1", forms: ["probleme", "problemen"] },
  { id: "Idee:N", lemma: "Idee", pos: "N", gender: "die", plural: "Ideen", english: "idea", rank: 219, cefr: "A1", forms: ["ideen"] },
  { id: "Beispiel:N", lemma: "Beispiel", pos: "N", gender: "das", plural: "Beispiele", english: "example (zum Beispiel = for example)", rank: 220, cefr: "A1", forms: ["beispiele"] },
  { id: "Geld:N", lemma: "Geld", pos: "N", gender: "das", english: "money", rank: 221, cefr: "A1", forms: [] },
  { id: "Euro:N", lemma: "Euro", pos: "N", gender: "der", plural: "Euro", english: "euro", rank: 222, cefr: "A1", forms: ["euros"] },
  { id: "Uhr:N", lemma: "Uhr", pos: "N", gender: "die", plural: "Uhren", english: "clock; o'clock (um drei Uhr)", rank: 223, cefr: "A1", forms: ["uhren"] },
  { id: "Stunde:N", lemma: "Stunde", pos: "N", gender: "die", plural: "Stunden", english: "hour", rank: 224, cefr: "A1", forms: ["stunden"] },
  { id: "Moment:N", lemma: "Moment", pos: "N", gender: "der", plural: "Momente", english: "moment (Moment mal! = hang on)", rank: 225, cefr: "A1", forms: ["momente"] },
  { id: "Woche:N", lemma: "Woche", pos: "N", gender: "die", plural: "Wochen", english: "week", rank: 226, cefr: "A1", forms: ["wochen"] },
  { id: "Wochenende:N", lemma: "Wochenende", pos: "N", gender: "das", plural: "Wochenenden", english: "weekend", rank: 227, cefr: "A1", forms: ["wochenenden"] },
  { id: "Morgen:N", lemma: "Morgen", pos: "N", gender: "der", plural: "Morgen", english: "morning", rank: 228, cefr: "A1", forms: ["morgens"] },
  { id: "Abend:N", lemma: "Abend", pos: "N", gender: "der", plural: "Abende", english: "evening", rank: 229, cefr: "A1", forms: ["abende", "abends"] },
  { id: "Nacht:N", lemma: "Nacht", pos: "N", gender: "die", plural: "Nächte", english: "night", rank: 230, cefr: "A1", forms: ["nächte", "nachts"] },
  { id: "Familie:N", lemma: "Familie", pos: "N", gender: "die", plural: "Familien", english: "family", rank: 231, cefr: "A1", forms: ["familien"] },
  { id: "Mutter:N", lemma: "Mutter", pos: "N", gender: "die", plural: "Mütter", english: "mother", rank: 232, cefr: "A1", forms: ["mütter"] },
  { id: "Vater:N", lemma: "Vater", pos: "N", gender: "der", plural: "Väter", english: "father", rank: 233, cefr: "A1", forms: ["väter"] },
  { id: "Eltern:N", lemma: "Eltern", pos: "N", gender: "die", english: "parents (plural only)", rank: 234, cefr: "A1", forms: [] },
  { id: "Bruder:N", lemma: "Bruder", pos: "N", gender: "der", plural: "Brüder", english: "brother", rank: 235, cefr: "A1", forms: ["brüder"] },
  { id: "Schwester:N", lemma: "Schwester", pos: "N", gender: "die", plural: "Schwestern", english: "sister", rank: 236, cefr: "A1", forms: ["schwestern"] },
  { id: "Freund:N", lemma: "Freund", pos: "N", gender: "der", plural: "Freunde", english: "friend; boyfriend", rank: 237, cefr: "A1", forms: ["freunde", "freunden"] },
  { id: "Freundin:N", lemma: "Freundin", pos: "N", gender: "die", plural: "Freundinnen", english: "friend (f); girlfriend", rank: 238, cefr: "A1", forms: ["freundinnen"] },
  { id: "Name:N", lemma: "Name", pos: "N", gender: "der", plural: "Namen", english: "name", rank: 239, cefr: "A1", forms: ["namen", "namens"] },
  { id: "Wohnung:N", lemma: "Wohnung", pos: "N", gender: "die", plural: "Wohnungen", english: "flat, apartment", rank: 240, cefr: "A1", forms: ["wohnungen"] },
  { id: "Zimmer:N", lemma: "Zimmer", pos: "N", gender: "das", plural: "Zimmer", english: "room", rank: 241, cefr: "A1", forms: ["zimmern"] },
  { id: "Tür:N", lemma: "Tür", pos: "N", gender: "die", plural: "Türen", english: "door", rank: 242, cefr: "A1", forms: ["türen"] },
  { id: "Tisch:N", lemma: "Tisch", pos: "N", gender: "der", plural: "Tische", english: "table", rank: 243, cefr: "A1", forms: ["tische"] },
  { id: "Bett:N", lemma: "Bett", pos: "N", gender: "das", plural: "Betten", english: "bed", rank: 244, cefr: "A1", forms: ["betten"] },
  { id: "Küche:N", lemma: "Küche", pos: "N", gender: "die", plural: "Küchen", english: "kitchen", rank: 245, cefr: "A1", forms: ["küchen"] },
  { id: "Wasser:N", lemma: "Wasser", pos: "N", gender: "das", english: "water", rank: 246, cefr: "A1", forms: [] },
  { id: "Bier:N", lemma: "Bier", pos: "N", gender: "das", plural: "Biere", english: "beer", rank: 247, cefr: "A1", forms: ["biere"] },
  { id: "Brot:N", lemma: "Brot", pos: "N", gender: "das", plural: "Brote", english: "bread", rank: 248, cefr: "A1", forms: ["brote"] },
  { id: "Brötchen:N", lemma: "Brötchen", pos: "N", gender: "das", plural: "Brötchen", english: "bread roll", rank: 249, cefr: "A1", forms: [] },
  { id: "Kaffee:N", lemma: "Kaffee", pos: "N", gender: "der", plural: "Kaffees", english: "coffee", rank: 250, cefr: "A1", forms: ["kaffees"] },
  { id: "Milch:N", lemma: "Milch", pos: "N", gender: "die", english: "milk", rank: 251, cefr: "A1", forms: [] },
  { id: "Essen:N", lemma: "Essen", pos: "N", gender: "das", plural: "Essen", english: "food, meal", rank: 252, cefr: "A1", forms: [] },
  { id: "Apfel:N", lemma: "Apfel", pos: "N", gender: "der", plural: "Äpfel", english: "apple", rank: 253, cefr: "A1", forms: ["äpfel"] },
  { id: "Bäckerei:N", lemma: "Bäckerei", pos: "N", gender: "die", plural: "Bäckereien", english: "bakery", rank: 254, cefr: "A1", forms: ["bäckereien", "bäcker"] },
  { id: "Restaurant:N", lemma: "Restaurant", pos: "N", gender: "das", plural: "Restaurants", english: "restaurant", rank: 255, cefr: "A1", forms: ["restaurants"] },
  { id: "Hunger:N", lemma: "Hunger", pos: "N", gender: "der", english: "hunger (Hunger haben = to be hungry)", rank: 256, cefr: "A1", forms: [] },
  { id: "Stadt:N", lemma: "Stadt", pos: "N", gender: "die", plural: "Städte", english: "city, town", rank: 257, cefr: "A1", forms: ["städte"] },
  { id: "Straße:N", lemma: "Straße", pos: "N", gender: "die", plural: "Straßen", english: "street", rank: 258, cefr: "A1", forms: ["straßen"] },
  { id: "Bahnhof:N", lemma: "Bahnhof", pos: "N", gender: "der", plural: "Bahnhöfe", english: "train station", rank: 259, cefr: "A1", forms: ["bahnhöfe"] },
  { id: "Zug:N", lemma: "Zug", pos: "N", gender: "der", plural: "Züge", english: "train", rank: 260, cefr: "A1", forms: ["züge"] },
  { id: "Bus:N", lemma: "Bus", pos: "N", gender: "der", plural: "Busse", english: "bus", rank: 261, cefr: "A1", forms: ["busse"] },
  { id: "Auto:N", lemma: "Auto", pos: "N", gender: "das", plural: "Autos", english: "car", rank: 262, cefr: "A1", forms: ["autos"] },
  { id: "Fahrrad:N", lemma: "Fahrrad", pos: "N", gender: "das", plural: "Fahrräder", english: "bicycle", rank: 263, cefr: "A1", forms: ["fahrräder", "rad"] },
  { id: "Weg:N", lemma: "Weg", pos: "N", gender: "der", plural: "Wege", english: "way, path", rank: 264, cefr: "A1", forms: ["wege"] },
  { id: "Platz:N", lemma: "Platz", pos: "N", gender: "der", plural: "Plätze", english: "place, square; seat; room", rank: 265, cefr: "A1", forms: ["plätze"] },
  { id: "Supermarkt:N", lemma: "Supermarkt", pos: "N", gender: "der", plural: "Supermärkte", english: "supermarket", rank: 266, cefr: "A1", forms: ["supermärkte"] },
  { id: "Arbeit:N", lemma: "Arbeit", pos: "N", gender: "die", plural: "Arbeiten", english: "work, job", rank: 267, cefr: "A1", forms: ["arbeiten"] },
  { id: "Schule:N", lemma: "Schule", pos: "N", gender: "die", plural: "Schulen", english: "school", rank: 268, cefr: "A1", forms: ["schulen"] },
  { id: "Arzt:N", lemma: "Arzt", pos: "N", gender: "der", plural: "Ärzte", english: "doctor", rank: 269, cefr: "A1", forms: ["ärzte", "ärztin"] },
  { id: "Termin:N", lemma: "Termin", pos: "N", gender: "der", plural: "Termine", english: "appointment", rank: 270, cefr: "A1", forms: ["termine"] },
  { id: "Kopf:N", lemma: "Kopf", pos: "N", gender: "der", plural: "Köpfe", english: "head", rank: 271, cefr: "A1", forms: ["köpfe"] },
  { id: "Hand:N", lemma: "Hand", pos: "N", gender: "die", plural: "Hände", english: "hand", rank: 272, cefr: "A1", forms: ["hände", "händen"] },
  { id: "Wetter:N", lemma: "Wetter", pos: "N", gender: "das", english: "weather", rank: 273, cefr: "A1", forms: [] },
  { id: "Sonne:N", lemma: "Sonne", pos: "N", gender: "die", plural: "Sonnen", english: "sun", rank: 274, cefr: "A1", forms: [] },
  { id: "Rechnung:N", lemma: "Rechnung", pos: "N", gender: "die", plural: "Rechnungen", english: "bill, invoice", rank: 275, cefr: "A1", forms: ["rechnungen"] },
  { id: "Sprache:N", lemma: "Sprache", pos: "N", gender: "die", plural: "Sprachen", english: "language", rank: 276, cefr: "A1", forms: ["sprachen"] },
  { id: "Wort:N", lemma: "Wort", pos: "N", gender: "das", plural: "Wörter", english: "word", rank: 277, cefr: "A1", forms: ["wörter", "worte"] },
  { id: "Land:N", lemma: "Land", pos: "N", gender: "das", plural: "Länder", english: "country; countryside", rank: 278, cefr: "A1", forms: ["länder", "ländern"] },
  { id: "Spaß:N", lemma: "Spaß", pos: "N", gender: "der", english: "fun (Spaß machen = to be fun)", rank: 279, cefr: "A1", forms: [] },
  { id: "Glück:N", lemma: "Glück", pos: "N", gender: "das", english: "luck; happiness", rank: 280, cefr: "A1", forms: [] },
  { id: "Ahnung:N", lemma: "Ahnung", pos: "N", gender: "die", plural: "Ahnungen", english: "clue (keine Ahnung! = no idea)", rank: 281, cefr: "A2", forms: [], tags: ["colloquial"] },
  { id: "Entschuldigung:N", lemma: "Entschuldigung", pos: "N", gender: "die", plural: "Entschuldigungen", english: "excuse me; apology", rank: 282, cefr: "A1", forms: ["sorry"] },
  { id: "Hilfe:N", lemma: "Hilfe", pos: "N", gender: "die", plural: "Hilfen", english: "help", rank: 283, cefr: "A1", forms: [] },

  // ── Numbers (~284–297) ───────────────────────────────────────────
  { id: "eins:NUM", lemma: "eins", pos: "NUM", english: "one", rank: 284, cefr: "A1", forms: [] },
  { id: "zwei:NUM", lemma: "zwei", pos: "NUM", english: "two", rank: 285, cefr: "A1", forms: ["zwo"] },
  { id: "drei:NUM", lemma: "drei", pos: "NUM", english: "three", rank: 286, cefr: "A1", forms: [] },
  { id: "vier:NUM", lemma: "vier", pos: "NUM", english: "four", rank: 287, cefr: "A1", forms: [] },
  { id: "fünf:NUM", lemma: "fünf", pos: "NUM", english: "five", rank: 288, cefr: "A1", forms: [] },
  { id: "sechs:NUM", lemma: "sechs", pos: "NUM", english: "six", rank: 289, cefr: "A1", forms: [] },
  { id: "sieben:NUM", lemma: "sieben", pos: "NUM", english: "seven", rank: 290, cefr: "A1", forms: [] },
  { id: "acht:NUM", lemma: "acht", pos: "NUM", english: "eight", rank: 291, cefr: "A1", forms: [] },
  { id: "neun:NUM", lemma: "neun", pos: "NUM", english: "nine", rank: 292, cefr: "A1", forms: [] },
  { id: "zehn:NUM", lemma: "zehn", pos: "NUM", english: "ten", rank: 293, cefr: "A1", forms: [] },
  { id: "elf:NUM", lemma: "elf", pos: "NUM", english: "eleven", rank: 294, cefr: "A1", forms: [] },
  { id: "zwölf:NUM", lemma: "zwölf", pos: "NUM", english: "twelve", rank: 295, cefr: "A1", forms: [] },
  { id: "zwanzig:NUM", lemma: "zwanzig", pos: "NUM", english: "twenty", rank: 296, cefr: "A1", forms: [] },
  { id: "hundert:NUM", lemma: "hundert", pos: "NUM", english: "hundred", rank: 297, cefr: "A1", forms: [] },

  // ── Farewell (~298) ──────────────────────────────────────────────
  { id: "tschüss:INTJ", lemma: "tschüss", pos: "INTJ", english: "bye", rank: 298, cefr: "A1", forms: ["tschüs", "ciao"], tags: ["colloquial"] },
];
